### ISSUE TITLE
License for the code?

### ISSUE THREAD

**Issue by lightweight** [nzpug/code-of-conduct#3]
Many thanks for making this code available on Github. I have just forked it for the benefit of the NZOSS (see https://git.nzoss.org.nz/lightweight/nzoss-code-of-conduct ). I am wondering if there's any reason not to formally license this under, say, a Creative Commons by-SA license... As it is, I'm technically infringing on copyright by creating a derivative work...

**Comment by dannyadair** [comment]
I think we just never thought about it. Don't see why we wouldn't - will check with the committee.

**Comment by lightweight** [comment]
Cool :)

**Comment by mwhudson** [comment]
Yes, makes sense.

**Comment by dannyadair** [comment]
Not all members have responded yet but we do have a majority already. We'll add a corresponding note shortly.

**Comment by dannyadair** [comment]
Note has now been added, see bottom of https://github.com/nzpug/code-of-conduct/blob/master/code-of-conduct.md

**Comment by lightweight** [comment]
Superb, many thanks for your rapid response!
